/**
 *                               Copyrigth 2020
 *
 *       Licensed under the Apache License, Version 2.0 (the "License");
 *       you may not use this file except in compliance with the License.
 *       You may obtain a copy of the License at
 *
 *                   http://www.apache.org/licenses/LICENSE-2.0
 *
 *       Unless required by applicable law or agreed to in writing, software
 *       distributed under the License is distributed on an "AS IS" BASIS,
 *       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *       See the License for the specific language governing permissions and
 *       limitations under the License.
 */
package sprint4.provasprint4.forms.select;

import sprint4.provasprint4.classes.*;
import sprint4.provasprint4.classes.LlistaPresupostos;
import javax.swing.JLabel;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

import sprint4.provasprint4.forms.JFramePropostes;
import sprint4.provasprint4.forms.alta.JFrameAltaProjecte;
import sprint4.provasprint4.forms.modificar.JFrameModificarProjectes;

/**
 * JFramePropostaSeleccionar
 *
 * @author grup3 Ximo Bernaltes, Joel Ferragut, Marc España, Joel Pascual
 * @version 14.0
 */

/* Mitjançant aquest Frame seleccionem una proposta del llistat*/
public class JFramePropostaSeleccionar extends javax.swing.JFrame {

    /* Atributs de classe */
    public static LlistaEntitats ll_enti;
    public static LlistaProjectes ll_proj;
    public static LlistaPropostes ll_prop;
    public static LlistaPresupostos ll_pres;
    private int selectedItem = -1;
    public static int selectedItemProposta = -1;
    public static String titol_proj;
    public static String descripcio_proj;
    public static String data_alta;
    public static int opcio;

    /* Establim els paràmetres del Frame */
    public JFramePropostaSeleccionar(LlistaEntitats ll_enti, LlistaProjectes ll_proj, LlistaPropostes ll_prop,
                                     LlistaPresupostos ll_pres,  String titol_proj, String descripcio_proj,
                                     String data_alta, int opcio) {
        //Passar la llista creada al main com a paràmetre al instanciar la classe.
        this.setTitle("Gestió de Propostes"); //Definir títol de la finestra.
        try {
           // //Defineix l'estil de la finestra
        } catch (Exception e) {
            e.printStackTrace();
        }
        JFramePropostaSeleccionar.ll_enti = ll_enti;
        JFramePropostaSeleccionar.ll_proj = ll_proj;
        JFramePropostaSeleccionar.ll_prop = ll_prop;
        JFramePropostaSeleccionar.ll_pres = ll_pres;
        JFramePropostaSeleccionar.titol_proj = titol_proj;
        JFramePropostaSeleccionar.descripcio_proj = descripcio_proj;
        JFramePropostaSeleccionar.data_alta = data_alta;
        JFramePropostaSeleccionar.opcio = opcio;

        initComponents();
        grupsTitle.setHorizontalAlignment(JLabel.CENTER); // Fa que el text de grupsTitle estigui centrat al seu contenidor
        emplenarTaula("");
    }

    /* Mètode per a emplenar la taula de dades */
    public void emplenarTaula(String s) {
        Object columnNames[] = {"ID", "Nom", "Autor", "Descripcio", "Data Alta", "Data Baixa", "Estat"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);

        LlistaPropostes consulta = ll_prop.consulta(s);

        for (int i = 0; i < consulta.getNumPropostesActuals(); i++) {
            Proposta p = consulta.returnList().get(i);
            if (p.getEstat().equals("Activa")) {
                Object rowData[] = {p.getId(), p.getNom(), p.getAutor().getNom(), p.getDescripcio(), p.getDataAlta(), p.getDataBaixa(), p.getEstat()};
                model.addRow(rowData);
            }
        }
        taula_propostes.setModel(model);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupsTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taula_propostes = new javax.swing.JTable();
        searchGroups = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        grupsTitle.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        grupsTitle.setText("Propostes");
        grupsTitle.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                grupsTitleComponentHidden(evt);
            }
        });

        taula_propostes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        taula_propostes.getTableHeader().setReorderingAllowed(false);
        taula_propostes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taula_propostesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(taula_propostes);

        searchGroups.setText("Search...");
        searchGroups.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchGroupsFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchGroupsFocusLost(evt);
            }
        });
        searchGroups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchGroupsActionPerformed(evt);
            }
        });
        searchGroups.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchGroupsKeyTyped(evt);
            }
        });

        jButton1.setText("Seleccionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(grupsTitle)
                        .addGap(53, 53, 53)
                        .addComponent(searchGroups, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(searchGroups, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(grupsTitle)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchGroupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchGroupsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchGroupsActionPerformed

    private void grupsTitleComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_grupsTitleComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_grupsTitleComponentHidden

    private void searchGroupsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchGroupsFocusGained
        // TODO add your handling code here:
        if (searchGroups.getText().equals("Search...")) {
            searchGroups.setText("");
        }
    }//GEN-LAST:event_searchGroupsFocusGained

    private void searchGroupsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchGroupsFocusLost
        // TODO add your handling code here:
        if (searchGroups.getText().length() == 0) {
            //searchGroups.setText("Search...");
        }
    }//GEN-LAST:event_searchGroupsFocusLost

    private void taula_propostesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taula_propostesMouseClicked
        selectedItemProposta = (int) taula_propostes.getValueAt(taula_propostes.getSelectedRow(), 0) - 1; // Cada vegada que fem click a algun element de la taula
//fem que l'atribut selectedItem s'actualitzi per a que sigui l'id de l'element
    }//GEN-LAST:event_taula_propostesMouseClicked

    private void searchGroupsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchGroupsKeyTyped
        emplenarTaula(searchGroups.getText()); // Cada vegada que s'escriu al input s'actualitza la taula
    }//GEN-LAST:event_searchGroupsKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (opcio == 0) {
            JFrameAltaProjecte g_a = new JFrameAltaProjecte(ll_enti, ll_prop, ll_proj, ll_pres, selectedItemProposta, titol_proj, descripcio_proj); // Al fer click a afegirGrup, instanciem el jframe JFrameAltaProposta
            g_a.setVisible(true); // el fem visible
            dispose(); // i tanquem la finestra que estavem
        } else {
            JFrameModificarProjectes g_b = new JFrameModificarProjectes(ll_enti, ll_proj, ll_prop, ll_pres, selectedItemProposta, titol_proj, descripcio_proj, data_alta);
            g_b.setVisible(true); // el fem visible
            dispose(); // i tanquem la finestra que estavem
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePropostes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePropostes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePropostes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePropostes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePropostes(ll_enti, ll_proj, ll_prop,ll_pres).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel grupsTitle;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField searchGroups;
    private javax.swing.JTable taula_propostes;
    // End of variables declaration//GEN-END:variables
}
