/**
 *                               Copyrigth 2020
 *
 *       Licensed under the Apache License, Version 2.0 (the "License");
 *       you may not use this file except in compliance with the License.
 *       You may obtain a copy of the License at
 *
 *                   http://www.apache.org/licenses/LICENSE-2.0
 *
 *       Unless required by applicable law or agreed to in writing, software
 *       distributed under the License is distributed on an "AS IS" BASIS,
 *       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *       See the License for the specific language governing permissions and
 *       limitations under the License.
 */
package sprint4.provasprint4.forms;

import javax.swing.UIManager;
import sprint4.provasprint4.classes.*;
import static sprint4.provasprint4.forms.alta.JFrameAltaProposta.ll_enti;
import static sprint4.provasprint4.forms.alta.JFrameAltaProposta.ll_proj;
import static sprint4.provasprint4.forms.alta.JFrameAltaProposta.ll_prop;

/**
 * JFrameProjectes
 *
 * @author grup3 Ximo Bernaltes, Joel Ferragut, Marc España, Joel Pascual
 * @version 14.0
 */

/* Mitjançant aquest Frame escollirem el que volem gestionar*/
public class JFrameMenuPrincipal extends javax.swing.JFrame {

    /* Atributs de classe */
  public static LlistaEntitats ll_enti;
    public static LlistaProjectes ll_proj;
    public static LlistaPropostes ll_prop;
    public static LlistaPresupostos ll_pres;


    /* Establim els paràmetres del Frame */
    public JFrameMenuPrincipal(LlistaEntitats llista_enti, LlistaProjectes llista_proj, LlistaPropostes llista_prop,
                               LlistaPresupostos ll_pres) {
        this.setTitle("Gestió d'Empreses");
        try {
            JFrameMenuPrincipal.ll_enti = llista_enti;
            JFrameMenuPrincipal.ll_proj = llista_proj;
            JFrameMenuPrincipal.ll_prop = llista_prop;
            JFrameMenuPrincipal.ll_pres = ll_pres;
            initComponents();
            setLocationRelativeTo(null);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        javax.swing.JButton projectesBtn = new javax.swing.JButton();
        // Variables declaration - do not modify                     
        javax.swing.JButton entitatsBtn = new javax.swing.JButton();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JButton propostesBtn = new javax.swing.JButton();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JButton presupostosBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        projectesBtn.setText("Gestió Projectes");
        projectesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                projectesBtnMouseClicked(evt);
            }
        });
        projectesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectesBtnActionPerformed(evt);
            }
        });

        entitatsBtn.setText("Gestió Entitats");
        entitatsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entitatsBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Waree", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestió d'empreses");

        propostesBtn.setText("Gestió Propostes");
        propostesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propostesBtnActionPerformed(evt);
            }
        });

        presupostosBtn.setText("Gestió Presupostos");
        presupostosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt){
                pressupostosBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(entitatsBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(propostesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(presupostosBtn,javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(projectesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(100, 100, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(projectesBtn)
                .addGap(39, 39, 39)
                .addComponent(entitatsBtn)
                .addGap(39, 39, 39)
                .addComponent(propostesBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                    .addComponent(presupostosBtn)
                    .addGap(39, 39, 39)
            )
        );

        pack();
    }// </editor-fold>                        

    private void projectesBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projectesBtnMouseClicked
    }//GEN-LAST:event_projectesBtnMouseClicked

    private void entitatsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entitatsBtnActionPerformed
        /* Obri el frame per a la gestió d'entitats */
        JFrameEntitats a = new JFrameEntitats(ll_enti, ll_proj, ll_prop, ll_pres);
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_entitatsBtnActionPerformed

    private void projectesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectesBtnActionPerformed
        /* Obri el frame per a la gestió de projectes */
        JFrameProjectes a = new JFrameProjectes(ll_enti, ll_proj, ll_prop,ll_pres);
        a.setVisible(true);
        dispose();    }//GEN-LAST:event_projectesBtnActionPerformed

    private void propostesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propostesBtnActionPerformed
        /* Obri el frame per a la gestió de propostes */
        JFramePropostes a = new JFramePropostes(ll_enti, ll_proj, ll_prop,ll_pres);
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_propostesBtnActionPerformed
    private void pressupostosBtnActionPerformed(java.awt.event.ActionEvent evt) {                                             
        /* Obri el frame per a la gestió de propostes */
        JFramePressupostos a = new JFramePressupostos(ll_enti, ll_proj, ll_prop,ll_pres);
        a.setVisible(true);
        dispose();
    }                                               
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMenuPrincipal(ll_enti, ll_proj, ll_prop,ll_pres).setVisible(true);
            }
        });
    }

    // End of variables declaration                   
}
