/**
 *                               Copyrigth 2020
 *
 *       Licensed under the Apache License, Version 2.0 (the "License");
 *       you may not use this file except in compliance with the License.
 *       You may obtain a copy of the License at
 *
 *                   http://www.apache.org/licenses/LICENSE-2.0
 *
 *       Unless required by applicable law or agreed to in writing, software
 *       distributed under the License is distributed on an "AS IS" BASIS,
 *       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *       See the License for the specific language governing permissions and
 *       limitations under the License.
 */
package sprint4.provasprint4.forms.modificar;

import sprint4.provasprint4.classes.*;
import sprint4.provasprint4.forms.JFramePressupostos;
import sprint4.provasprint4.forms.JFramePropostes;
import sprint4.provasprint4.forms.alta.JFrameAltaPressupost;
import sprint4.provasprint4.forms.select.JFrameEntitatSeleccionar;

import javax.swing.*;

/**
 * JFrameProjectes
 *
 * @author grup3 Ximo Bernaltes, Joel Ferragut, Marc España, Joel Pascual
 * @version 14.0
 */

/* Mitjançant aquest Frame durem a terme la modificació de propostes*/
public class JFrameModificarPressuposts extends javax.swing.JFrame {

    /* Atributs de classe */
    static int selectedItem = -1;
    public static LlistaEntitats ll_enti;
    public static LlistaProjectes ll_proj;
    public static LlistaPropostes ll_prop;
    public static LlistaPresupostos ll_pres;
    public static int selectedItemEntitat = -1;
    public static int opcio = 1;
    public static String nom;
    public static String descripcio;
    public static String data_alta;
    public static String en;
    public static String nom_cost;
    public static String preu_cos;
    public static String quantitat_cost;
    public static String estat_proposta;
    public static String estat;
    private Pressupost pres;

    /* Establim els paràmetres del Frame */
    public JFrameModificarPressuposts(LlistaEntitats llista_enti, LlistaPropostes llista_prop,
                                      LlistaProjectes llista_proj, LlistaPresupostos llista_pres, int selectedItem) {
        try {
           //
            ll_enti = llista_enti;
            ll_proj = llista_proj;
            ll_prop = llista_prop;
            ll_pres = llista_pres;
            JFrameModificarPressuposts.selectedItem = selectedItem;
            initComponents();

            pres = ll_pres.returnList().get(selectedItem);
            field_nom.setText(pres.getNom());
            field_descripcio.setText(pres.getDescripcio());
            field_dataAlta.setText(pres.getDataAlta());
            field_entitat.setText(pres.getProjecte().getNom());
            if ("Activa".equals(pres.getEstat())) {
                botoAlta.setVisible(false);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /* Establim els paràmetres del Frame */
    public JFrameModificarPressuposts(LlistaEntitats llista_enti, LlistaPropostes llista_prop, LlistaProjectes llista_proj,
                                      LlistaPresupostos llista_pres , int selectedItemEntitat, String nom, String descripcio, String data_alta) {
        try {
           //
            ll_enti = llista_enti;
            ll_proj = llista_proj;
            ll_prop = llista_prop;
            ll_pres = llista_pres;
            JFrameModificarPressuposts.selectedItemEntitat = selectedItemEntitat;
            JFrameModificarPressuposts.nom = nom;
            JFrameModificarPressuposts.descripcio = descripcio;
            JFrameModificarPressuposts.data_alta = data_alta;

            initComponents();

            pres = ll_pres.returnList().get(selectedItem);
            if (selectedItemEntitat != -1) {
                //Agafar el valor de l'entitat d'una taula
                Entitat e = ll_enti.returnList().get(selectedItemEntitat);
                field_entitat.setText(e.getNom());
                en = e.getNom();
            }
            field_nom.setText(pres.getNom());
            field_descripcio.setText(pres.getDescripcio());
            field_dataAlta.setText(pres.getDataAlta());
            field_entitat.setText(en);
            if ("Activa".equals(pres.getEstat())) {
                botoAlta.setVisible(false);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabel jLabel1 = new JLabel();
        JButton modificarPressupost = new JButton();
        field_nom = new javax.swing.JTextField();
        JLabel jLabel2 = new JLabel();
        field_descripcio = new javax.swing.JTextField();
        JLabel jLabel3 = new JLabel();
        JButton enrere = new JButton();
        JLabel jLabel4 = new JLabel();
        field_dataAlta = new javax.swing.JTextField();
        botoAlta = new javax.swing.JButton();
        JButton jButton1 = new JButton();
        field_entitat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nom");

        modificarPressupost.setText("Aceptar");
        modificarPressupost.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificarPressupostMouseClicked(evt);
            }
        });
        modificarPressupost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarPressupostActionPerformed(evt);
            }
        });

        field_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_nomActionPerformed(evt);
            }
        });

        jLabel2.setText("Descripció");

        field_descripcio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_descripcioActionPerformed(evt);
            }
        });

        jLabel3.setText("Entitat");

        enrere.setText("Cancelar");
        enrere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enrereMouseClicked(evt);
            }
        });

        jLabel4.setText("Data d'alta");

        field_dataAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_dataAltaActionPerformed(evt);
            }
        });

        botoAlta.setText("Alta");
        botoAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoAltaActionPerformed(evt);
            }
        });

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        field_entitat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        field_entitat.setText("Selecciona una entitat");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(field_nom)
                            .addComponent(field_descripcio)
                            .addComponent(field_dataAlta)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(field_entitat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botoAlta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(modificarPressupost, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                                .addComponent(enrere, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)))))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(field_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(field_descripcio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButton1)
                    .addComponent(field_entitat))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(field_dataAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botoAlta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificarPressupost)
                    .addComponent(enrere))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void field_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_nomActionPerformed

    private void field_descripcioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_descripcioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_descripcioActionPerformed

    private void modificarPressupostMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarPressupostMouseClicked
        //Mostrem missatge de confirmació
        int confirm = JOptionPane.showConfirmDialog(this, "Esteu segurs de modificar aquest pressupost?");
        if (confirm == JOptionPane.YES_OPTION) {
            if (pres.getEstat().equals("Activa")) {
                //Cridem al metode per a modificar les dades
                Projecte proj = ll_proj.buscarPerNom(field_entitat.getText(), selectedItemEntitat);
                ll_pres.modificarPressupost(selectedItem, field_nom.getText(), field_descripcio.getText(), proj, field_dataAlta.getText(), "", "Activa");
            } else {
                //Cridem al metode per a modificar les dades
                Projecte projecte = ll_proj.buscarPerNom(field_entitat.getText(), selectedItemEntitat);
                ll_pres.modificarPressupost(selectedItem, field_nom.getText(), field_descripcio.getText(), projecte, field_dataAlta.getText(), pres.getDataBaixa(), "Inactiva");
            }
            enrereMouseClicked(evt);
        }
    }//GEN-LAST:event_modificarPressupostMouseClicked

    private void enrereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enrereMouseClicked
        JFramePressupostos pp = new JFramePressupostos(ll_enti, ll_proj, ll_prop,ll_pres);
        pp.setVisible(true);
        dispose();
    }//GEN-LAST:event_enrereMouseClicked

    private void modificarPressupostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarPressupostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarPressupostActionPerformed

    private void botoAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoAltaActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Esteu segurs de modificar aquesta proposta?");
        if (confirm == JOptionPane.YES_OPTION) {
            //Metode que retorna una entitat, passantli el seu nom i id.
            Projecte projecte = ll_proj.buscarPerNom(field_entitat.getText(), selectedItemEntitat);
            System.out.println(pres.getEstat());
            //Donar d'alta una matricula que esta de baixa
            ll_pres.modificarPressupost(selectedItem, field_nom.getText(), field_descripcio.getText(), projecte, field_dataAlta.getText(), "", "Activa");

            // Tornem a la finestra principal
            JFramePressupostos principalWindow = new JFramePressupostos(ll_enti, ll_proj, ll_prop,ll_pres);
            principalWindow.setVisible(true);       //la fem visible
            dispose();                             //eliminem la finestra actual      
        }
    }//GEN-LAST:event_botoAltaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Tornem a la finestra principal
        JFrameEntitatSeleccionar ju = new JFrameEntitatSeleccionar(ll_enti, ll_proj, ll_prop, ll_pres,
                field_nom.getText(),
                field_descripcio.getText(), opcio, field_dataAlta.getText());
        ju.setVisible(true);       //la fem visible
        dispose(); //eliminem la finestra actual        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void field_dataAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_dataAltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_dataAltaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameModificarPressuposts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameModificarPressuposts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameModificarPressuposts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameModificarPressuposts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameModificarPressuposts(ll_enti, ll_prop, ll_proj,ll_pres, selectedItem).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoAlta;
    private javax.swing.JTextField field_dataAlta;
    private javax.swing.JTextField field_descripcio;
    private javax.swing.JLabel field_entitat;
    private javax.swing.JTextField field_nom;
    // End of variables declaration//GEN-END:variables
}
