/**
 *                               Copyrigth 2020
 *
 *       Licensed under the Apache License, Version 2.0 (the "License");
 *       you may not use this file except in compliance with the License.
 *       You may obtain a copy of the License at
 *
 *                   http://www.apache.org/licenses/LICENSE-2.0
 *
 *       Unless required by applicable law or agreed to in writing, software
 *       distributed under the License is distributed on an "AS IS" BASIS,
 *       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *       See the License for the specific language governing permissions and
 *       limitations under the License.
 */
package Sprint4.provasprint4.forms.alta;

import javax.swing.UIManager;
import Sprint4.provasprint4.classes.LlistaEntitats;
import Sprint4.provasprint4.classes.LlistaProjectes;
import Sprint4.provasprint4.classes.LlistaPropostes;
import Sprint4.provasprint4.classes.Proposta;
import Sprint4.provasprint4.classes.LlistaPresupostos;
import Sprint4.provasprint4.forms.JFrameProjectes;
import Sprint4.provasprint4.forms.select.JFramePropostaSeleccionar;
import javax.swing.JOptionPane;

import static Sprint4.provasprint4.forms.alta.JFrameAltaEntitat.ll_pres;

/**
 * JFrameAltaProjecte
 *
 * @author grup3 Ximo Bernaltes, Joel Ferragut, Marc España, Joel Pascual
 * @version 14.0
 */

/* Mitjançant aquest Frame durem a terme l'alta de projectes*/
public class JFrameAltaProjecte extends javax.swing.JFrame {

    /* Atributs de classe */
  public static LlistaEntitats ll_enti;
    public static LlistaProjectes ll_proj;
    public static LlistaPropostes ll_prop;
    public static LlistaPresupostos ll_pres;
    public static int selectedItemProjecte = -1;
    public static String titol;
    public static String descripcio;
    public String prop;
    public static int opcio = 0;
    public String data_alta;

    /* Establim els paràmetres del Frame */
    public JFrameAltaProjecte(LlistaEntitats ll_enti, LlistaProjectes ll_proj, LlistaPropostes ll_prop, LlistaPresupostos ll_pres) {
        try {
           //
        } catch (Exception e) {
            e.printStackTrace();
        }
        JFrameAltaProjecte.ll_enti = ll_enti;
        JFrameAltaProjecte.ll_proj = ll_proj;
        JFrameAltaProjecte.ll_prop = ll_prop;
        JFrameAltaProjecte.ll_pres = ll_pres;

        initComponents();
    }

    /* Establim els paràmetres del Frame */

    public JFrameAltaProjecte(LlistaEntitats ll_enti, LlistaPropostes ll_prop, LlistaProjectes ll_proj, LlistaPresupostos ll_pres,
                              int selectedItemProjecte, String titol, String descripcio) {
        try {
           //
            JFrameAltaProjecte.selectedItemProjecte = selectedItemProjecte;
            JFrameAltaProjecte.ll_enti = ll_enti;
            JFrameAltaProjecte.ll_proj = ll_proj;
            JFrameAltaProjecte.ll_prop = ll_prop;
            JFrameAltaProjecte.ll_pres = ll_pres;
            JFrameAltaProjecte.titol = titol;
            JFrameAltaProjecte.descripcio = descripcio;
            initComponents();
            //Mostrem un altre cop els valors introduits inicialment
            field_nom.setText(titol);
            field_descripcio.setText(descripcio);
            System.out.println(selectedItemProjecte);

            if (selectedItemProjecte != -1) {
                //Agafar el valor de l'entitat d'una taula
                Proposta p = ll_prop.returnList().get(selectedItemProjecte);
                camp_proposta.setText(p.getNom());
                prop = p.getNom();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        altaProjecte = new javax.swing.JButton();
        field_nom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        field_descripcio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        enrere = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        camp_proposta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Titol");

        altaProjecte.setText("Acceptar");
        altaProjecte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                altaProjecteMouseClicked(evt);
            }
        });
        altaProjecte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaProjecteActionPerformed(evt);
            }
        });

        field_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_nomActionPerformed(evt);
            }
        });

        jLabel2.setText("Descripció");

        field_descripcio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_descripcioActionPerformed(evt);
            }
        });

        jLabel3.setText("Proposta");

        enrere.setText("Cancel·lar");
        enrere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enrereMouseClicked(evt);
            }
        });

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        camp_proposta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        camp_proposta.setText("Selecciona una proposta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(33, 33, 33)
                                .addComponent(camp_proposta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(15, 15, 15))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(field_nom)
                                    .addComponent(field_descripcio))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(altaProjecte, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(enrere, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 120, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(field_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(field_descripcio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButton1)
                    .addComponent(camp_proposta))
                .addGap(18, 18, 18)
                .addComponent(altaProjecte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enrere)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void field_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_nomActionPerformed

    private void field_descripcioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_descripcioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_descripcioActionPerformed

    private void altaProjecteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_altaProjecteMouseClicked
        if (field_nom.getText().equals("") || field_descripcio.equals("")) {
            //Mostrem error si no selecciona res
            JOptionPane.showMessageDialog(this, "Per favor, introdueix les dades", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            Proposta prop = ll_prop.buscarPerNom(camp_proposta.getText(), selectedItemProjecte);
            System.out.println(prop);
            ll_proj.inserirProjecte(field_nom.getText(), field_descripcio.getText(), prop);
            enrereMouseClicked(evt);
        }
    }//GEN-LAST:event_altaProjecteMouseClicked

    private void enrereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enrereMouseClicked
        JFrameProjectes pp = new JFrameProjectes(ll_enti, ll_proj, ll_prop,ll_pres);
        pp.setVisible(true);
        dispose();
    }//GEN-LAST:event_enrereMouseClicked

    private void altaProjecteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaProjecteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_altaProjecteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Tornem a la finestra principal
        JFramePropostaSeleccionar ju = new JFramePropostaSeleccionar(ll_enti, ll_proj, ll_prop, ll_pres, field_nom.getText(), field_descripcio.getText(), data_alta, opcio);
        ju.setVisible(true);       //la fem visible
        dispose(); //eliminem la finestra actual        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAltaProjecte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAltaProjecte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAltaProjecte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAltaProjecte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAltaProjecte(ll_enti, ll_proj, ll_prop,ll_pres).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton altaProjecte;
    private javax.swing.JLabel camp_proposta;
    private javax.swing.JButton enrere;
    private javax.swing.JTextField field_descripcio;
    private javax.swing.JTextField field_nom;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
